spring.application.name=gestao-acoes-corretoras
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update

# API Keys
api.brapi.token=YOUR_BRAPI_TOKEN
api.alphavantage.key=YOUR_ALPHAVANTAGE_KEY

# Cache config
spring.cache.type=simple